export const SELECTCARTYPE = "SELECT * FROM CAR_TYPE ORDER BY code;";
export const SELECTCARINFO = "SELECT * FROM CAR_INFO ORDER BY cid;";
export const SELECTRENTORDER = "SELECT * FROM RENT_ORDER ORDER BY oid;";
